In [ ]:
l1 = [1,2,3,4]
l2=[3,4,5,6]
add=[a+b for a,b in zip(l1,l2)]
print(add)
#add this two list elementwise

[4, 6, 8, 10]


In [ ]:
#Find maximum element combining two list l1 and l2
l1=[1,2,3,4]
l2=[3,4,5,6]
maximum_element=max(l1+l2)
print(maximum_element)

6


In [ ]:
#find common elements from list l1 and l1
l1=[1,2,3,4]
l2=[3,4,5,6]
common_elements=list(set(l1) & set(l2))
print(common_elements)

[3, 4]


In [ ]:
d1 = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
d2 = {'a': 7, 'f': 2, 'g': 55, 'h': "101"}

#find common key from d1 and d2
common_keys=set(d1.keys()) & set(d2.keys())
print(common_keys)
#find common value from d1 and d2
common_values=set(d1.values()) & set(d2.values())
print(common_values)

{'a'}
{2}


In [ ]:
#replace the values of d1 to their negative value
d1 = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
d2 = {'a': 7, 'f': 2, 'g': 55, 'h': "101"}
d1={k:-v for k,v in d1.items()}
print(d1)

{'a': -1, 'b': -2, 'c': -3, 'd': -4}


In [ ]:
#replace key to value and value to key in d2
d2 = {'a': 7, 'f': 2, 'g': 55, 'h': "101"}
d2={v:k for k,v in d2.items()}
print(d2)


{7: 'a', 2: 'f', 55: 'g', '101': 'h'}


In [ ]:
#create an array of random numbers
import numpy as np
array=np.random.rand(10)
print(array)

[0.15413344 0.8227242  0.85507877 0.28123392 0.04913141 0.04559171
 0.82270888 0.09168999 0.1698436  0.14137535]


In [ ]:
#to create an array with sequence of numbers within a specified range
array=np.arange(10,20)
print(array)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
#To create array filled wih zeros
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#To create array filled with ones
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
