In [5]:
#create any 3 dimensional array and practice indexing
import numpy as np
array=np.array([[[10,11,12],[12,13,14],[15,16,17]]])
print(array)

[[[10 11 12]
  [12 13 14]
  [15 16 17]]]


In [8]:
print(array[0,1,2])

14


In [16]:
#create array of suqares of keys of below dictionary
#d = {1:2,2:3,3:4,4:5}
d = {1:2,2:3,3:4,4:5}
keys=d.keys()
squares=[i**2 for i in keys]
array=np.array(squares)
array

array([ 1,  4,  9, 16])

In [17]:
# multiply any 2 dim array to identity matrix (2*2) and comment on result
array_1=np.array([[5,6],[6,7]])
array_2=np.eye(2,2)
array_3=array_1*array_2
print(array_3)

[[5. 0.]
 [0. 7.]]
